config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :post_attachments
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :rental_properties
  root "application#landing"

  get '/listing' => 'rental_properties#l'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
  geocoded_by :address
  after_validation :geocode

  has_many :locations, dependent: :destroy
  accepts_nested_attributes_for :locations, allow_destroy: true, :reject_if => :all_blank
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :promotions
  has_and_belongs_to_many :users

  paginates_per 6
  scope :business_filter, -> (params, business_ids) {
    where(
      "id IN (#{business_ids.present? ? business_ids.join(',') : 'NULL'})"
    ).price_industry_filter(params).order_by(params, business_ids).page(params[:page])
  }

  scope :price_industry_filter, -> (params){
    if params[:price].blank? && params[:industry].present?
      where('industry = ?', params[:industry])
    elsif params[:price].present? && params[:industry].blank?
      where('price <= ?', params[:price])
    elsif params[:price].present? && params[:industry].present?
      where('price <= ? AND industry = ?', params[:price], params[:industry])
    end
  }

  scope :order_by, -> (params, business_ids){
    if params[:order_by].blank? || params[:order_by] == "distance"
      order(Arel.sql(business_ids.map{|x| "id = #{x} desc"}.join(", ")))
    else
      order(Arel.sql("#{params[:order_by]} #{params[:order_to]}"))
    end
  }

end

app/models/location.rb
class Location < ApplicationRecord
  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  geocoded_by :address
  after_validation :geocode

  belongs_to :business

  scope :filter_location, -> (params, user_location){
    near(
      params[:location].present? ? params[:location] : user_location,
      params[:miles].present? ? params[:miles] : 25000
    )
  }

end

app/models/promotion.rb
class Promotion < ApplicationRecord
  has_and_belongs_to_many :businesses 
end

app/models/rental_property.rb
class RentalProperty < ApplicationRecord
  geocoded_by :address
  after_validation :geocode
  belongs_to :user

  scope :rental_property_filter, -> (params){
    if params[:price].blank? && params[:industry].blank?
      all
    elsif params[:price].blank? && params[:industry].present?
      where('industry = ?', params[:industry])
    elsif params[:price].present? && params[:industry].blank?
      where('price >= ?', params[:price])
    else
      where('price >= ? AND industry = ?', params[:price], params[:industry])
    end
  }

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :businesses
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :rental_properties

  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  validate :validate_username
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  attr_accessor :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  INDUSTRIES_FOR_SELECT = ["", "Gym", "Crossfit"].freeze

  def landing
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  before_action :set_business, only: [
    :show,
    :edit,
    :update,
    :destroy
  ]

  before_action :set_location_for_business, only: [
    :show,
    :index
  ]

  before_action :set_type_device, only: :show

  def index
    set_businesses
    @indusries_for_selest = INDUSTRIES_FOR_SELECT
    respond_to do |format|
      format.js
      format.html
    end
  end

  def new
    @indusries_for_selest = INDUSTRIES_FOR_SELECT
    @business = Business.new
    @business.locations.build
  end

  def create
    @business = current_user.businesses.new(business_params)
    respond_to do |format|
      if @business.save
        format.js {render :created}
      else
        format.js {render :created_error}
      end
    end
  end

  def show; end

  def edit
    @indusries_for_selest = INDUSTRIES_FOR_SELECT
  end

  def update
      @business.update(business_params)
      respond_to do |format|
        format.js {render :updated}
    end
  end

  def destroy
    respond_to do |format|
      if @business.destroy
        format.js {render :destroyed}
      else
        format.js {render :destroyed_error}
      end
    end
  end

  private

  def set_location_for_business
    @location_business = get_location
  end

  def set_business
    @business = Business.find(params[:id])
  end

  def get_location
    loc = request.location
    logger.debug("location #{loc.latitude} #{loc.longitude}")
    if loc.latitude.nil? || loc.longitude.nil?
      return [43.6307863, -74.4659275]
    else
      return [loc.latitude, loc.longitude]
    end
  end

  def set_businesses
    @businesses = Business.business_filter(
      params,
      Location.filter_location(params, @location_business).map{|l| l.business_id}
    )
  end

  def business_params
    params.require(:business).permit(
      :title,
      :description,
      :price,
      :address,
      :user_id,
      :email,
      :industry,
      :male,
      :female,
      :age_range_from,
      :age_range_to,
      locations_attributes: [
        :id,
        :_destroy,
        :business_id,
        :description,
        :address,
        :image
      ]
    )
  end
end

app/controllers/rental_properties_controller.rb
class RentalPropertiesController < ApplicationController

  before_action :set_rental_property, only: [
    :show,
    :edit,
    :update,
    :destroy
  ]

  before_action :set_location, only: [
    :show,
    :index
  ]

  def index
    @rental_properties = RentalProperty.rental_property_filter(params)
    @indusries_for_selest = INDUSTRIES_FOR_SELECT

    respond_to do |format|
      format.js
      format.html
    end
  end

  def new
    @indusries_for_selest = INDUSTRIES_FOR_SELECT
    @rental_property = RentalProperty.new
  end

  def create
    @rental_propertyset_rental_property = current_user.rental_properties.new(rental_property_params)
    respond_to do |format|
      if @rental_property.save
        format.js {render :created}
      else
        format.js {render :created_error}
      end
    end
  end

  def show; end

  def edit
    respond_to do |format|
      format.js {render :edited}
    end
  end

  def update
      @rental_property.update(rental_property_params)
      respond_to do |format|
        format.js {render :updated}
    end
  end

  def destroy
    respond_to do |format|
      if @rental_property.destroy
        format.js {render :destroyed}
      else
        format.js {render :destroyed_error}
      end
    end
  end

  private

  def set_location
    @location = get_location
  end

  def set_rental_property
    @rental_property = RentalProperty.find(params[:id])
  end

  def get_location
    loc = request.location
    logger.debug("location #{loc.latitude} #{loc.longitude}")
    if loc.latitude.nil? || loc.longitude.nil?
      return [43.6307863, -74.4659275]
    else
      return [loc.latitude, loc.longitude]
    end
  end

  def rental_property_params
    params.require(:rental_property).permit(:title, :description, :address, :price, :user_id, :email, :industry) #email?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper

end

app/helpers/rental_properties_helper.rb
module RentalPropertiesHelper

end

app/views/application/landing.html.erb
<div class="mainbody">
  <div class="search_area">
    <h1>Browse through our listings of fitness centers today.</h1>
    <%= link_to rental_properties_path, :action => 'go' do %>
      <div class="search_bar">
        <div class="search_text">Find Your Spot...</div>
      </div>
    <% end %>
  </div>
</div>
<div class="cities row">
  <div class="offset-sm-1 col-sm-2">
    <p>Syracuse</p>
  </div>
  <div class="offset-sm-2 col-sm-2">
    <p>Fairfield County</p>
  </div>
  <div class="offset-sm-2 col-sm-2">
    <p>Westchester</p>
  </div>
</div>
<div id="about">
  <div class="row">
    <div class="slogan-section">
      <h1>Connecting Brands in Health and Fitness</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-xl-6 about-container">
      <div class="about-title">
        <h1>About</h1>
      </div>
      <div class="about-text">
        <p>Adzilly is an innovative online platform focused on brand collaboration in the health and fitness industry. We are building an ecosystem to connect brands with other businesses that share a similar customer base. We specialize in experiential campaigns, product placement and print promotions. The physical marketing channel we have established is targeted, affordable and captures consumers at the right place and in the right time.</p>
        <div class="button-navigate">
          <%= link_to("Get in touch", "mailto: matt.winters@adzilly.com") %>
        </div>
      </div>
    </div>
    <div class="col-xl-6 about-container">
      <div class="about-video">
        <iframe allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" frameborder="0" height="315" src="https://www.youtube.com/embed/J38fk16dllM" width="560"></iframe>
      </div>
    </div>
  </div>
  <div id="meet-the-founders">
    <div class="row">
      <div class="meet-us">
        <div class="meet-us-text">
          <h1>Meet The Founders</h1>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="offset-xl-3 col-xl-3">
        <div class="meet-us-headshot">
          <%= image_tag("winters_headshot.png", height: '300', width: '300') %>
        </div>
        <div class="meet-us-info">
          <h2>Matt Winters</h2>
          <p>Co-Founder</p>
        </div>
      </div>
      <div class="col-xl-3">
        <div class="meet-us-headshot">
          <%= image_tag("AbtHeadshot.png", height: '300', width: '275') %>
        </div>
        <div class="meet-us-info">
          <h2>Matthew Abt</h2>
          <p>Co-Founder</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/businesses/_business_list.html.erb
<div id="listings__locations-items">
  <% @businesses.each do |business| %>
    <div class="listings__locations-item-container">
      <div class="listings__locations-item">
        <div class="listings__locations-slider-container">
          <button class="listings__slider-button listings__slider-button-prev">
            <%= image_tag("show-images/arrow-slider.svg", class:"listings__locations-slider-prev-icon") %>
          </button>
          <div class="listings__locations-slider">
            <%= business.locations.each do |location| %>
              <%= image_tag(location.image.url, class:"listings__locations-slider-image") %>
            <% end %>
          </div>
          <button class="listings__slider-button listings__slider-button-next">
            <%= image_tag("show-images/arrow-slider.svg", class:"listings__locations-slider-next-icon") %>
          </button>
        </div>
        <%= link_to "#{business.title}", business_path(business), class: "listings__item-title-link" %>
        <p class="listings__item-description"><%= business.description %></p>
        <div class="listings__item-price-distance-container">
          <div class="listings__item-price-distance">
            <%= image_tag("show-images/show-icon-marker.svg", class:"listings__locations-distance-icon") %>
            <p class="listings__item-price-distance-text">
              <%= number_to_human(business.distance_from(@location_business), units: {unit: "mi"}) || "Unknown" %>
            </p>
          </div>
          <div class="listings__item-price-distance">
            <%= image_tag("show-images/show-icon-money.svg", class:"listings__locations-price-icon") %>
            <p class="listings__item-price-distance-text">
              <%= "#{number_to_currency(business.price)} /per month" %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="listings__item-paginate">
    <%= paginate @businesses, remote: true %>
  </div>
</div>

app/views/businesses/_filter_form.html.erb
<%= form_tag businesses_path(action: 'index'), class: "listings__filter-form", method: :get, remote: true do %>
  <div class="listings__filter-field-block">
    <%= label_tag :price, "Maximum price", class: "listings__filter-label" %>
    <%= number_field_tag :price, @price, placeholder:"Your text here", class: "listings__filter-field listings__filter-field-number", min: "0" %>
  </div>
  <div class="listings__filter-field-block">
    <%= label_tag :industry, "Industry",class: "listings__filter-label" %>
    <%= select_tag :industry, options_for_select(@indusries_for_selest), class: "listings__filter-field listings__filter-field-select" %>
  </div>
  <div class="listings__filter-field-block">
    <%= label_tag :miles, "Within", class: "listings__filter-label" %>
    <%= number_field_tag :miles, @miles, placeholder:"Your text here", class: "listings__filter-field listings__filter-field-number", min: "0" %>
  </div>
  <div class="listings__filter-field-block">
    <%= label_tag :location, "Miles of", class: "listings__filter-label" %>
    <%= text_field_tag :location, @filter_location, placeholder:"Your text here", class: "listings__filter-field" %>
  </div>
  <div class="listings__filter-submit-block">
    <%= submit_tag "Filter", class: "listings__filter-submit-button" %>
    <%= link_to('Clear', businesses_path(:clear => true), class: "listings__filter-clear-button") %>
  </div>
<% end %>

app/views/businesses/_form.html.erb
<%= form_for(@business, remote: true) do |f| %>

  <div class="new-business__field-text-block">
    <%= f.label :title, class: "new-business__label" %>
    <%= f.text_field :title, type: "text", required: "true", class: "new-business__field" %>
  </div>
  <div class="new-business__field-text-block">
    <%= f.label :description, class: "new-business__label" %>
    <%= f.text_area :description, type: "text", required: "true", class: "new-business__field new-business__field-description" %>
  </div>
  <div class="new-business__field-text-block">
    <div class="new-business__row">
      <%= f.label :email, class: "new-business__label" %>
      <%= f.text_field :email, type: "text", required: "true", class: "new-business__field" %>
    </div>
    <div class="new-business__row">
      <%= f.label :price, class: "new-business__label" %>
      <%= f.text_field :price, type: "integral", required: "true", class: "new-business__field" %>
    </div>
  </div>
  <div class="new-business__field-text-block new-business__field-text-block-select">
    <div class="new-business__industry-male-female">
      <%= f.label :industry, class: "new-business__label" %>
      <%= f.select(:industry, options_for_select(@indusries_for_selest)) %>
    </div>
    <div class="new-business__industry-male-female">
      <%= f.label :male, class: "new-business__label" %>
      <%= f.text_field :male, type: "float", class: "new-business__field" %>
    </div>
    <div class="new-business__industry-male-female">
      <%= f.label :female, class: "new-business__label" %>
      <%= f.text_field :female, type: "float", class: "new-business__field" %>
    </div>
  </div>
  <div class="new-business__field-text-block">
    <div class="new-business__row">
      <%= f.label :age_range_from, class: "new-business__label" %>
      <%= f.text_field :age_range_from, type: "integral", class: "new-business__field" %>
    </div>
    <div class="new-business__row">
      <%= f.label :age_range_to, class: "new-business__label" %>
      <%= f.text_field :age_range_to, type: "integral", class: "new-business__field" %>
    </div>
  </div>
  <h2 class="new-business__locations-title">Locations</h2>
  <%= f.fields_for :locations, html: { multipart: true } do |location| %>
  <div class="new-business__add-location-container">
    <div class="new-business__add-location">
      <button type="button" title="Delete location" class="new-business__delete-location"></button>
      <div class="new-business__field-text-block">
        <%= location.label :description, class: "new-business__label" %>
        <%= location.text_area :description, type: "text", class: "new-business__field new-business__field-description new-business__reset-fields" %>
      </div>
      <div class="new-business__field-text-block">
        <%= location.label :address, class: "new-business__label" %>
        <%= location.text_field :address, type: "text", class: "new-business__field new-business__reset-fields" %>
      </div>
      <div class="new-business__field-text-block new-business__field-text-block-image">
        <%= location.label :"add-new-photo", "Add new photo",class: "new-business__label new-business__label-image" %>
        <%= location.file_field :"add-new-photo", class: "new-business__add-photo new-business__reset-fields" %>
        <%= image_tag("noimage.png", accept:'image/*', alt:"Image preview...", class:"new-business__image-location-preview") %>
      </div>
    </div>
  </div>
  <% end %>
  <div class="new-business__field-text-block">
    <button type="button" class="new-business__add-new-location">+ Add new location</button>
  </div>
  <div class="new-business__field-text-block-submit">
    <%= f.submit "Create Business", type: "submit", class: "new-business__create" %>
    <%= link_to('Back to businesses list', businesses_path, class: "new-business__back-listings-page") %>
  </div>
<% end %>

app/views/businesses/_show_desktop.html.erb
<section class="business__description">
  <div class="business__description-content">
    <div class="business__description-information">
      <div class="business__title-information">
        <h2 class="business__title-business">
          <%= @business.title %>
        </h2>
        <p class="business__description-business">
          <%= @business.description %>
        </p>
      </div>
      <div class="business__slider-images">
        <button class="business__slider-button business__slider-button-prev">
          <%= image_tag("show-images/arrow-slider.svg", class:"business__slider-button-image business__slider-button-image-prev") %>
        </button>
        <div class="business__slider-container">
          <div id="business__slider-images-container">
            <%= image_tag("show-images/slide1.png", class:"business__slider-image") %>
            <%= image_tag("show-images/slide2.png", class:"business__slider-image") %>
            <%= image_tag("show-images/slide3.png", class:"business__slider-image") %>
            <%= image_tag("show-images/trendy-youth-media-v1xjlra7F40-unsplash.png", class:"business__slider-image") %>
          </div>
        </div>
        <button class="business__slider-button business__slider-button-next">
          <%= image_tag("show-images/arrow-slider.svg", class:"business__slider-button-image business__slider-button-image-next") %>
        </button>
      </div>
    </div>
    <div id="business__general-image-block" class="business__general-image-block">
      <%= image_tag("show-images/trendy-youth-media-v1xjlra7F40-unsplash.png", class:"business__general-image") %>
    </div>
  </div>
</section>
<section class="business__information">
  <div class="business__information-content">
    <h2 class="business__information-title">Information</h2>
    <div class="business__information-items">
      <div class="business__information-item">
        <p class="business__information-item-title">
          <%= image_tag("show-images/show-icon-world.svg", class:"business__information-item-icon") %>
          Address
        </p>
        <span class="business__information-item-description">
          <%= @business.address %>
        </span>
      </div>
      <div class="business__information-item">
        <p class="business__information-item-title">
          <%= image_tag("show-images/show-icon-marker.svg", class:"business__information-item-icon") %>
          Distance
        </p>
        <span class="business__information-item-description">
          <%= "#{number_to_human(@business.distance_from(@location_business), units: {unit: 'mi'}) || 'Unknown distance'} away from you." %>
        </span>
      </div>
      <div class="business__information-item">
        <p class="business__information-item-title">
          <%= image_tag("show-images/show-icon-money.svg", class:"business__information-item-icon") %>
          Price
        </p>
        <span class="business__information-item-description">
          <%= "#{number_to_currency(@business.price)}/per month." %>
        </span>
      </div>
    </div>
  </div>
</section>

app/views/businesses/edit.html.erb
<%= render "form" %>

app/views/businesses/index.js.erb
document.getElementById("listings__locations-items").innerHTML = "<%= escape_javascript(render 'business_list') %>";
document.dispatchEvent(new CustomEvent("listingsSlider"));

app/views/businesses/new.html.erb
<div class="new-business__background">
  <div class="new-business__container">
    <h1 class="new-business__title">
      <span class="new-business__title-green">Add new</span>
      Listing
    </h1>
    <%= render "form" %>
  </div>
</div>

app/views/businesses/show.html.erb
<%=render "show_#{@device_for_render}"%>

app/views/layouts/_header.html.erb
<div class="container-fluid">
  <div class="row">
    <% flash.each do |key, value| %>
      <div class="alert-<%= key %> alert"></div>
      <strong>
        <%= value %>
      </strong>
    <% end %>
  </div>
  <div class="row">
    <div class="col-sm-4 logo">
      <%= link_to image_tag("logo_plain.png", :width => 200, :height => 75), root_path %>
    </div>
    <% if user_signed_in? %>
      <div class="col-md-2">
        <div class="button-login">
          <div class="user-info">
            <span>
              <%= "hello, #{current_user.username}" %>
            </span>
          </div>
          <%= link_to 'logout', destroy_user_session_path, method: :delete, :class => 'btn btn-primary btn-sm' %>
        </div>
      </div>
    <% else %>
      <div class="col-sm-8">
        <%= link_to('Sign Up', new_user_registration_path, :class => 'button-header-navigation') %>
        <%= link_to('Sign In', new_user_session_path, :class => 'button-header-navigation') %>
        <%= link_to('Listings', rental_properties_path, :class => 'button-header-navigation') %>
        <%= link_to('About', root_path(anchor: 'about'), :class => 'button-header-navigation') %>
      </div>
      <button class="dropbtn" onclick="myFunction()">Dropdown</button>
      <div class="dropdown-content" id="myDropdown">
        <%= link_to('About', root_path(anchor: 'about')) %>
        <%= link_to('Listings', rental_properties_path) %>
        <%= link_to('Sign In', new_user_session_path) %>
        <%= link_to('Sign Up', new_user_registration_path) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <title>Adzilly</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/rental_properties/_filter_form.html.erb
<%= form_tag rental_properties_path(action: 'index'), method: "get", remote: true %>
  <%= hidden_field_tag :filter, true %>

  <%= label_tag :price, "Maximum price" %>
  <%= number_field_tag :price, @price %>

  <%= label_tag :industry %>
  <%= select_tag :industry, options_for_select(@indusries_for_selest) %>

  <%= label_tag :miles, "Within" %>
  <%= number_field_tag :miles, @miles %>

  <%= label_tag :filter_location, "miles of" %>
  <%= text_field_tag :filter_location, @filter_location %>

  <div class="submit">
    <%= submit_tag "Filter" %>
    <%= link_to('Clear', rental_properties_path(:clear => true)) %>
  </div>

app/views/rental_properties/edit.html.erb
<% flash.each do |key, value| %>
  <div class="alert-<%= key %> alert"></div>
<% end %>
<button class="close" type="submit"><% :data => { :dismiss => "alert" } %></button>
<strong>
  <%= value %>
    <% if user_signed_in? %>
      <% if current_user.id != @property.user_id %>
        <% redirect_to rental_property_path(@property) %>
      <% end %>
    <% else %>
      <% redirect_to rental_property_path(@property) %>
  <% end %>
</strong>
<div class="container" id="main">
  <div class="form">
    <%= form_for @property, :method => :patch do |f| %>
      <%= render "create_update_form", f: f %>
      <%= f.submit %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="middle">
    <div class="button-navigate">
      <%= link_to('cancel changes', rental_property_path(@property)) %>
    </div>
  </div>
</div>

app/views/rental_properties/index.html.erb
<div class="container" id="main">
  <div class="filter">
    <%= render "filter_form" %>
  </div>
  <h3 class="header">Available locations</h3>
  <table class="table">
    <thead>
      <tr>
        <th class="column">
          <%= link_to('Property', rental_properties_path(:order => 'title')) %>
        </th>
        <th class="column">Description</th>
        <th class="column">
          <%= link_to('Distance from you', rental_properties_path(:order => 'distance')) %>
        </th>
        <th class="column">
          <%= link_to('Asking Price', rental_properties_path(:order => 'price')) %>
        </th>
        <th class="images">Images</th>
      </tr>
    </thead>
    <tbody>
      <% @rental_properties.each do |prop| %>
        <tr class="property">
          <td class="title">
            <%= link_to "#{prop.title}", rental_property_path(prop) %>
          </td>
          <td class="description">
            <%= truncate(prop.description,length: 60) %>
          </td>
          <td class="details">
            <%= number_to_human(prop.distance_from(@location), units: {unit: "mi"}) || "Unknown" %>
          </td>
          <td class="price">
            <%= "#{number_to_currency(prop.price)} /per month" %>
          </td>
          <% if prop.image_url %>
            <td class="images">
              <%= image_tag "https://adzilly.s3.us-east-2.amazonaws.com/no_image.jpeg" %>
            </td>
          <% else %>
            <td class="images">
              <%= image_tag "https://adzilly.s3.us-east-2.amazonaws.com/no_image.jpeg" %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row">
    <div class="col-md-offset-1"></div>
    <% if user_signed_in? %>
      <div class="col-md-3 button-navigate">
        <%= link_to('Create a new listing', new_rental_property_path) %>
      </div>
    <% else %>
      <div class="col-md-3 button-navigate">
        <%= link_to('Create a new listing', new_user_registration_path) %>
      </div>
    <% end %>
  </div>
</div>

app/views/rental_properties/new.html.erb
<div class="container" id="main">
  <div class="form">
    <%= render "form" %>
  </div>
  <div class="row">
    <div class="middle">
      <div class="button-navigate">
        <%= link_to('Back to rental properties list', rental_properties_path) %>
      </div>
    </div>
  </div>
</div>

app/views/rental_properties/show.html.erb
<div class="container" id="main">
  <div class="row">
    <% if user_signed_in? %>
      <div class="button-navigate">
        <%= link_to("Buy Now!", "mailto:#{@rental_property.email}") %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <h1 class="header title">
      <%= @rental_property.title %>
    </h1>
  </div>
  <% count = 0 %>
  <% @rental_property.images.each do |p| %>
    <% count +=1 %>
    <div class="show_image">
      <%= image_tag(p, height: '125', width: '175') %>
    </div>
    <% if count % 3 == 0 %>
      <br/>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-offset-2"></div>
    <div class="col-md-8 description">
      <%= @rental_property.description %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-offset-2"></div>
    <div class="col-md-8 description">
      <%= "The property is located at #{@rental_property.address}" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-offset-2"></div>
    <div class="col-md-4 distance">
      <%= "#{number_to_human(@rental_property.distance_from(@location), units: {unit: 'mi'}) || 'Unknown distance'} away from you." %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 price">
      <% "{number_to_currency(@rental_property.price)}/per month." %>
    </div>
  </div>
  <div class="row">
    <div class="button-navigate">
      <%= link_to('Back', rental_properties_path) %>
    </div>
    <% if current_user&.id == @rental_property.user_id %>
      <div class="button-navigate">
        <%= link_to('Edit', edit_rental_property_path(@rental_property)) %>
      </div>
      <div class="button-navigate">
        <%= link_to('Remove', rental_property_path(@rental_property), method: :delete) %>
      </div>
    <% end %>
  </div>
</div>